version: '3.7'
services:
  postgres:
    image: postgres:12.4-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgressql"
    networks:
      - db_network
    volumes:
      - C:\Workspace\sandbox\sandbox-docker\database_postgres\data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@pgadmin.org"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    networks:
      - db_network
    depends_on:
      - postgres
networks:
  db_network:
    driver: bridge
volumes:
  postgres_data: